name: pyfar
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - numpy>=1.14.0
  - matplotlib
  - scipy>=1.5.0
  - libsndfile
  - pip:
    - urllib3
    - deepdiff
    - soundfile>=0.11.0
    - sofar>=0.1.2
    - pyfar
